export const resumeLink="https://drive.google.com/file/d/1Gb1dPGjy1Vg86Lpebuk97IguIahIfjQr/view?usp=sharing"
export const twitterLink="https://twitter.com/mjxshrivastava"
export const linkedinLink="https://www.linkedin.com/in/mrityunjay-shrivastava/"
export const githubLink="https://github.com/Mrityunjay20"
export const emaillink="mjxworks@gmail.com"